eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# turbine配置在这里
turbine:
  appConfig: sc-hello-service,sc-provider-service # 设置需要收集监控信息的服务名
  clusterNameExpression: "'default'" # 设置集群的名称